# from configs.inference_config import get_args
import json
import warnings

import numpy as np

warnings.filterwarnings("ignore")

from utils.annotation.agreement import get_human_score_agreement, get_kappa_agreement, get_krippendorff_agreement, get_per_class_krippendorff_agreement, get_human_human_kappa_agreement, get_human_human_score_agreement, get_first_sensation_accuracy, get_hierarchy_first_sensation_agreement


if __name__ == '__main__':
    
    # human_annotations = json.load(open('../Data/PittAd/train/human_human_datahuman_1_parsed.json'))
    
    # print('-' * 100)
    # print('Human-Human Agreement')
    # human_local_annotations = json.load(open(
    #     '../Data/PittAd/train/human_human_datahuman_2_parsed.json'))
    # print(len(human_local_annotations))
    # get_human_human_kappa_agreement(human_local_annotations, human_annotations)
    # # get_human_human_score_agreement(human_local_annotations, human_annotations)
    
    # human_annotations = json.load(open('../Data/PittAd/train/sensation_annotations_parsed.json'))
    
    # print('-' * 100)
    # print('Human-Human Agreement')
    # human_local_annotations = json.load(open(
    #     '../Data/PittAd/train/human_agreement_local_annotation_parsed.json'))
    # print(len(human_local_annotations))
    # get_human_human_kappa_agreement(human_local_annotations, human_annotations)
    # # get_human_human_score_agreement(human_local_annotations, human_annotations)
    
    
  
    # print('LLAMA3-InternVL')
    # metrics = json.load(open('/Users/aysanaghazadeh/SensoryAds/LLM_generated_LLAMA3_instruct/gen_images_human_annotated_images_LLAMA3_instruct.json'))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # # get_krippendorff_agreement(metrics, human_annotations)
    
    # print('QWenLM-InternVL')
    # metrics = json.load(open('/Users/aysanaghazadeh/SensoryAds/LLM_generated_QWenLM/gen_images_human_annotated_images_QWenLM.json'))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # # get_krippendorff_agreement(metrics, human_annotations)
    
    # print('InternVL')
    # metrics = json.load(open('/Users/aysanaghazadeh/SensoryAds/MLLM_generated_InternVL/gen_images_human_annotated_images_InternVL.json'))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # # get_krippendorff_agreement(metrics, human_annotations)
    
    # print('QWenVL')
    # metrics = json.load(open('/Users/aysanaghazadeh/SensoryAds/MLLM_generated_QWenVL/gen_images_human_annotated_images_QWenVL.json'))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # get_krippendorff_agreement(metrics, human_annotations)
    # args = get_args()
    # human_annotations = json.load(open(args.sensation_annotations))
    # metrics = json.load(open(args.description_file))
    # human_1_annotations = json.load(open('../Data/PittAd/train/human_human_datahuman_1_parsed.json'))
    # human_2_annotations = json.load(open('../Data/PittAd/train/human_human_datahuman_2_parsed.json'))
    human_annotations = json.load(open('../Data/PittAd/train/sensation_annotations_parsed_1200_test.json'))
    # print('Agreement Computation Started')
    # print('-' * 100)
    # print('Human Human Agreement')
    # get_human_human_kappa_agreement(human_1_annotations, human_2_annotations)
    # get_human_human_score_agreement(human_1_annotations, human_2_annotations)
    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-208000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_sensation_annotations_parsed_1200_test_ALL_real_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_extended_annotation_LLAMA3_instruct13000.json'))
    print(len(metrics))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-160000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_sensation_annotations_parsed_1200_test_ALL_real_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_extended_annotation_LLAMA3_instruct10000.json'))
    print(len(metrics))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-144000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_sensation_annotations_parsed_1200_test_ALL_real_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_extended_annotation_LLAMA3_instruct9000.json'))
    print(len(metrics))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-30000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_sensation_annotations_parsed_1200_test_ALL_real_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_extended_annotation_LLAMA3_instruct30000.json'))
    print(len(metrics))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('VQAScore')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/VQA_score/IN_InternVL_sensation_annotations_parsed_1200_test_ALL_real_description_generation.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)
    exit()
    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-90000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_LLAMA3_instruct90000.json'))
    print(len(metrics))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    # print('-' * 100)
    # print('Evosense-LLAMA3-InternVL-5000')
    # metrics = json.load(open(
    #     '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_LLAMA3_instruct5000.json'))
    # print(len(metrics))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # get_krippendorff_agreement(metrics, human_annotations)
    
    # print('-' * 100)
    # print('Evosense-LLAMA3-InternVL-10000')
    # metrics = json.load(open(
    #     '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_LLAMA3_instruct10000.json'))
    # print(len(metrics))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # get_krippendorff_agreement(metrics, human_annotations)
    
    # print('-' * 100)
    # print('Evosense-LLAMA3-InternVL-15000')
    # metrics = json.load(open(
    #     '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_LLAMA3_instruct15000.json'))
    # print(len(metrics))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # get_krippendorff_agreement(metrics, human_annotations)
    
    # print('-' * 100)
    # print('Evosense-LLAMA3-InternVL-20000')
    # metrics = json.load(open(
    #     '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_my_HierarchicalCPO_data_annotation_LLAMA3_instruct55000.json'))
    # print(len(metrics))
    # get_human_score_agreement(metrics, human_annotations)
    # get_kappa_agreement(metrics, human_annotations)
    # get_krippendorff_agreement(metrics, human_annotations)
    # # get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('Evosense-LLAMA3-InternV-SFT-OnlyL-19000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_mySFT_LLAMA3_instruct19000.json'))
    print(len(metrics))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-CPO-Only-21000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_21000.json'))
    print(len(metrics))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('QWenVL-QWenLM Judge')
    metrics = json.load(open(
    '/Users/aysanaghazadeh/SensoryAds/LLM_QWenLM/IN_QWenVL_train_images_total_ALL_description_generation.json'))
    # get_first_sensation_accuracy(metrics, human_annotations)
    # get_hierarchy_first_sensation_agreement(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('InternVL-QWenLM Judge')
    metrics = json.load(open(
    '/Users/aysanaghazadeh/SensoryAds/LLM_QWenLM/IN_InternVL_train_images_total_ALL_description_generation.json'))
    # get_first_sensation_accuracy(metrics, human_annotations)
    # get_hierarchy_first_sensation_agreement(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('InternVL-LLAMA3_instruct Judge')
    metrics = json.load(open(
    '/Users/aysanaghazadeh/SensoryAds/LLM_LLAMA3_instruct/IN_InternVL_train_images_total_ALL_description_generation.json'))
    # get_first_sensation_accuracy(metrics, human_annotations)
    # get_hierarchy_first_sensation_agreement(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)
    
    print('-' * 100)
    print('QWenVL-LLAMA3_instruct Judge')
    metrics = json.load(open(
    '/Users/aysanaghazadeh/SensoryAds/LLM_LLAMA3_instruct/IN_QWenVL_train_images_total_ALL_description_generation.json'))
    # get_first_sensation_accuracy(metrics, human_annotations)
    # get_hierarchy_first_sensation_agreement(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-40000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_40000.json'))
    get_first_sensation_accuracy(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-30000')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_30000.json'))
    get_first_sensation_accuracy(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-25000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_24500.json'))
    get_first_sensation_accuracy(metrics, human_annotations)
    get_hierarchy_first_sensation_agreement(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-LLAMA3-InternVL-21000')
    metrics = json.load(open(
        '/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_21000.json'))
    get_first_sensation_accuracy(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-QWenLM-InternVL')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_QWenLM_finetunedTrue_30000.json'))
    get_first_sensation_accuracy(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-LLAMA3-QWenVL')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_QWenVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedTrue_30000.json'))
    get_first_sensation_accuracy(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-QWenLM-QWenVL')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_QWenVL_train_images_total_ALL_description_generation_QWenLM_finetunedTrue_25000.json'))
    get_first_sensation_accuracy(metrics, human_annotations)
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-QWenLM-InternVL_Zeroshot')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_QWenLM_finetunedFalse.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Evosense-LLAMA3-InternVL_Zeroshot')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Evosense_LLM/IN_InternVL_train_images_total_ALL_description_generation_LLAMA3_instruct_finetunedFalse.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('VQAScore')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/VQA_score/IN_InternVL_train_images_total_ALL_description_generation.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('PickScore')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/PickScore/IN_InternVL_train_images_total_ALL_description_generation.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('Image-Reward')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/Image_Reward/IN_InternVL_train_images_total_ALL_description_generation.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('CLIP-score')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/CLIPScore/IN_InternVL_train_images_total_ALL_description_generation.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-' * 100)
    print('MLLM - InternVL')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/MLLM/IN_InternVL_train_images_total_ALL_description_generation.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)

    print('-'*100)
    print('MLLM - QWenVL')
    metrics = json.load(open('/Users/aysanaghazadeh/experiments/results/SensoryAds/new_results/MLLM/IN_InternVL_train_images_total_ALL_description_generation.json'))
    get_human_score_agreement(metrics, human_annotations)
    get_kappa_agreement(metrics, human_annotations)
    get_krippendorff_agreement(metrics, human_annotations)
    # get_per_class_krippendorff_agreement(metrics, human_annotations)
