python evaluation.py --config_type=DEFAULT \
--evaluation_type=MLLM_generated \
--description_file=../experiments/results/SensoryAds/IN_InternVL_20250917_185403_AR_ALL_QWenImage_ALL_description_generation.csv \
--test_set_images=20250917_185403/AR_ALL_QWenImage \
--T2I_model=QWenImage \
--Image_type=generated \
--MLLM=InternVL \
--MLLM_prompt=MLLM_judge.jinja \
--resume=True
