accelerate launch --mixed_precision=bf16 train_Flux_LoRA.py \
  --pretrained_model_name_or_path="black-forest-labs/FLUX.1-dev" \
  --jsonl_for_train="../Data/PittAd/train/metadata.jsonl" \
  --image_column="image" \
  --conditioning_image_column="conditioning_image" \
  --caption_column="caption" \
  --output_dir="../models/flux_edit_lora" \
  --validation_prompt "Generate an image that evokes Comforting Warmth and conveys I should buy this car because it is luxurious." \
  --validation_image "../Data/PittAd/train_images_total/4/13534.jpg" \
  --validation_steps=2100 \
  --resolution=1024 \
  --train_batch_size=1 \
  --gradient_accumulation_steps=4 \
  --gradient_checkpointing \
  --learning_rate=1e-4 \
  --rank=32 \
  --lr_scheduler="constant" \
  --max_train_steps=2000
