python inference.py \
--config_type=DEFAULT \
--AD_type=ALL \
--inference_type=description_generation \
--MLLM_prompt=description_generation.jinja \
--model_type=MLLM \
--MLLM=Gemma \
--description_goal=image_descriptor \
--test_set_images=../experiments/generated_images/SensoryAds/20250916_122348/AR_ALL_Flux \
--test_set_QA=../experiments/results/SensoryAds/AR_ALL_Flux_20250916_122348.csv \
--resume=True