python inference.py \
--config_type=DEFAULT \
--AD_type=Sensation \
--Image_type=generated \
--inference_type=description_generation \
--MLLM_prompt=description_generation.jinja \
--model_type=MLLM \
--MLLM=InternVL \
--description_goal=image_descriptor \
--test_set_images=../experiments/generated_images/SensoryAds/20250918_034952/Sensation_SD3 \
--test_set_QA=../experiments/results/SensoryAds/Sensation_SD3_20250918_034952.csv \
--resume=True