python inference.py \
--config_type=DEFAULT \
--AD_type=ALL \
--Image_type=generated \
--inference_type=description_generation \
--MLLM_prompt=description_generation.jinja \
--model_type=MLLM \
--MLLM=InternVL \
--description_goal=image_descriptor \
--test_set_images=../Data/PittAd/train_images_total \
--test_set_QA=../Data/PittAd/train/ExtendedRealAdAnnotationsClean_list.csv \
--resume=True
