python inference.py \
--config_type=DEFAULT \
--AD_type=Sensation \
--Image_type=generated \
--inference_type=description_generation \
--MLLM_prompt=description_generation.jinja \
--model_type=MLLM \
--MLLM=QWenVL \
--description_goal=image_descriptor \
--test_set_images=../experiments/generated_images/SensoryAds/20250918_122527/Sensation_QWenImage \
--test_set_QA=../experiments/results/SensoryAds/Sensation_QWenImage_20250918_122527.csv \
--resume=True